stages:
  - build
  - deploy

build:
  stage: build
  artifacts:
    untracked: true
  script:
    - hugo version
    - hugo

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - echo -e "Deploying updates to GitHub..."
    - pwd
    - cd public
    - git init
    - git config core.sshCommand 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' 
    - git add -A
    - git config user.name "yongman"
    - git config user.email "yming0221@gmail.com"
    - git commit -m "rebuilding site `TZ="Asia/Shanghai" date +"%Y-%m-%d %H:%M:%S"`"
    - git remote add origin git@github.com:yongman/yongman.github.io.git
    - git push --force -u origin master
    - cd ..
