stages:
  - build
  - deploy

job 1:
  stage: build
  script: whoami

job 2:
  stage: build
  script:
    - hugo version

job 3:
  stage: deploy
  script:
    - hugo
    - echo -e "Deploying updates to GitHub..."
    - pwd
    - cd public
    - git add -A
    - git commit -m "rebuilding site `date`"
    - git push --force -u origin master
    - cd ..
