stages:
  - build
  - deploy

job 2:
  stage: build
  script:
    - hugo version

job 3:
  stage: deploy
  script:
    - hugo
    - echo -e "Deploying updates to GitHub..."
    - pwd
    - cd public
    - git init
    - git config core.sshCommand 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' 
    - git add -A
    - git config user.name "yongman"
    - git config user.email "yming0221@gmail.com"
    - git commit -m "rebuilding site `date`"
    - git remote add origin git@github.com:yongman/yongman.github.io.git
    - git push --force -u origin master
    - cd ..
