stages:
  - build
  - deploy

build:
  stage: build
  artifacts:
    paths:
      - public
  script:
    - hugo version
    - hugo

deploy:
  stage: deploy
  dependencies:
    - build
  cache:
    paths:
      - yongman.github.io
  script:
    - if [ ! -d "yongman.github.io" ];then git clone git@github.com:yongman/yongman.github.io.git;else cd yongman.github.io && git pull && cd -;fi
    - echo "Deploying updates to GitHub..."
    - pwd
    - rm yongman.github.io/* -r
    - cp public/* yongman.github.io/ -r
    - cd yongman.github.io
    - git config core.sshCommand 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' 
    - git add -A
    - git config user.name "yongman"
    - git config user.email "yming0221@gmail.com"
    - git commit -m "rebuilding site `TZ="Asia/Shanghai" date +"%Y-%m-%d %H:%M:%S"`" || true
    - git push --force -u origin master
    - cd ..
